disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - type_body_length
  - weak_delegate

opt_in_rules:
  - anyobject_protocol
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - fallthrough
  - identical_operands
  - indentation_width
  - legacy_multiple
  - nimble_operator
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - toggle_bool
  - unowned_variable_capture

excluded:
  - .build

# Rule configurations

identifier_name:
  min_length:
    warning: 2
    error: 2

function_parameter_count:
  warning: 10

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 150
  error: 250
  ignores_function_declarations: true

nesting:
  type_level:
    warning: 5
    error: 5
  statement_level:
    error: 5

private_unit_test:
  severity: error

type_name:
  min_length:
    error: 1
  max_length:
    warning: 50
    error: 100
