name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Mint
      run: |
        git clone https://github.com/yonaskolb/Mint.git /tmp/Mint
        cd /tmp/Mint
        swift run mint install yonaskolb/mint
    - name: Run SwiftLint
      run: mint run realm/SwiftLint
